### ISSUE TITLE
Jnpr.utils.sw NoneType error when defining Device

### ISSUE THREAD

**Issue by rml596** [Juniper/py-junos-eznc#1179]
I am trying to use PyEZ to upgrade a switch using [this guide](https://www.juniper.net/documentation/us/en/software/junos-pyez/junos-pyez-developer/topics/topic-map/junos-pyez-program-software-installing.html) and I'm getting the following error:
```shell
Traceback (most recent call last):
  File "junos_software_upgrade.py", line 60, in <module>
    upgradeSwitch(IP)
  File "junos_software_upgrade.py", line 18, in upgradeSwitch
    sw = SW(dev)
  File "/Users/robertlynch/Library/Python/3.8/lib/python/site-packages/jnpr/junos/utils/sw.py", line 95, in __init__
    "current_re" in dev.facts and "localre" in dev.facts["current_re"]
TypeError: argument of type 'NoneType' is not iterable
```
The error occurs when I define dev
```python
def upgradeSwitch(ip):
    dev=Device(host=ip, user=uname, password=passord)
    print(dev.facts)
    sw = SW(dev)
    dev.open()
    facts=dev.facts
    dev.close()
```

But it does not occur when dev is defined like 
```python
def upgradeSwitch(ip):
    with Device(host=ip, user=uname, password=passord) as dev:
        print(dev.facts)
        sw = SW(dev)
        dev.open()
        facts=dev.facts
```

I am not sure what the difference is between the two methods.

**Comment by dineshbaburam91** [comment]
@rml596  In non-working,  You are using the dev object in the SW() API as a parameter without creating the object. dev. open() will create the session with the device and hold its object. You should use dev.open() before passing the object to other API's.

In the working case, you use "with" context manager which will open the session and hold the object without calling dev.open() explicitly. This is the reason you are not seeing the issue. This is highly recommended instead of calling dev.open() explicitly.
