### ISSUE TITLE
Do not fail on warnings

### ISSUE THREAD

**Issue by XioNoX** [Juniper/py-junos-eznc#358]
Currently, if for example a load config returns warnings, the whole process will fail.
It would be useful to be able to ignore them.

I think that work kind of started in https://groups.google.com/d/msg/junos-python-ez/S2s0DnT_n3o/whUzKeOsmz4J

**Comment by shermdog** [comment]
Hi @XioNoX,

This is under consideration, but we may not change this behavior.
Juniper/py-junos-netconify#19

ncclient passes this back to us as an rpc-error - which is correct per the RFC https://tools.ietf.org/html/rfc4741#section-4.3

We are also only given back the first rpc-error instance from ncclient  leopoul/ncclient#54

Because of this, if we were to pass on a warning, it's very likely there could be a nested error we do not see that that should not be passed.

Further more there is larger community to support that generally relies on such guardrails within their automation.  We shouldn't be committing bad configs.

-Rick

**Comment by XioNoX** [comment]
Thanks for your reply, I'll follow that ncclient bug#
I guess that's just a point of view, but all of the warnings I'm getting are more notices than warnings (empty configuration blocks during a load, licences on a commit, etc.), and thus, not bad configs.
A preference to flip (off by default) could be a good way to satisfy both kind of users (who need it strict and not).

In the meantime, knowing all the risks, do you have a pointer or a quick hack to ignore warnings (at least on config load)?

**Comment by shermdog** [comment]
You can put the operation in a try/catch and snag the severity from the exception

*untested example*
```python
except ConfigLoadError as e:
    if e.rpc_error['severity'] == 'warning':
        pass
    else:
        raise
```

**Comment by shermdog** [comment]
We should be able to get this into 2.0.0 as the underlying mechanism will be supported in the next release of ncclient.

**Comment by vnitinv** [comment]
We got this out in 1.3.1
