### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by johnthagen** [Juniper/py-junos-eznc#375]
The README currently states:

> Installation requires Python 2.6 or 2.7...

Since [Python 2 is end-of-life](https://www.python.org/dev/peps/pep-0404/), what are the plans to support Python 3?

First steps would be:

- `from __future__ import absolute_import, division, print_function, unicode_literals`

- The future package: http://python-future.org/

- Or the six package: https://pythonhosted.org/six/

**Comment by shermdog** [comment]
Hi @johnthagen,

Python 3 support is something on our radar, but we are also dependent on several other libraries, namely ncclient that is not Python 3 compatible (which you've noted there also).  
leopoul/ncclient#9

The EOL date for Python 2.7 has been extended to 2020:  https://www.python.org/dev/peps/pep-0373/

Even after supporting Py3 we will have to maintain compatibility for 2.7 even longer due to EEOL dates of RHEL.

Both our framework and ncclient accept pull requests, so if this is something you would like to contribute towards that would be great.

Thanks,
-Rick

**Comment by johnthagen** [comment]
Thanks for the quick response Rick (@shermdog)

Looks like ncclient has a merge request already ready for Python 3.X support, so I will be watching that ticket.

https://github.com/leopoul/ncclient/pull/60

**Comment by leopoul** [comment]
Currently on a dev branch: https://github.com/leopoul/ncclient/tree/devpy3 
To be merged back really soon

Best,
L.

**Comment by vnitinv** [comment]
@johnthagen Python support is available under github code. Will be released under PyPI in upcoming days.
