### ISSUE TITLE
Inconsistent start_shell.run() return value 

### ISSUE THREAD

**Issue by akbhat** [Juniper/py-junos-eznc#432]
The tuple returned by run() in start_shell.py seems to vary making it difficult to parse the results. For example three consecutive runs of the shell command below to get the pid returned three slightly different tuples.

["ps -auxw | grep pfe | grep /usr/sbin | awk '{print $2}'", '\r\r\n', '1393\r\n1514\r\n', '% ']
["ps -auxw | grep pfe | grep /usr/sbin | awk '{print $2}'", '\r\r\n', '1393\r\n', '1514\r\n', '% ']
["ps -auxw | grep pfe | grep /usr/sbin | awk '{print $2}'", '\r\r\n', '1393\r\n1514\r\n% ']

**Comment by stacywsmith** [comment]
A quick look at the code shows that run() doesn't actually comply with it's documentation. Specifically, the return value is not as documented. 

The documentation says:

    def run(self, command, this=_SHELL_PROMPT):
        """
        Run a shell command and wait for the response.  The return is a
        tuple. The first item is True/False if exit-code is 0.  The second
        item is the output of the command.
        :param str command: the shell command to execute
        :param str this: the exected shell-prompt to wait for
        :returns: result of the executed shell command (str)
        .. note:: as a *side-effect* this method will set the ``self.last_ok``
                  property.  This property is set to ``True`` if ``$?`` is
                  "0"; indicating the last shell command was successful.
        """

In reality, run() does set self.last_ok, but it does not return True/False as the first item in the tuple. It also doesn't return a string. It returns a tuple of strings. The strings are randomly broken up, as @akbhat reported, as they are read from the connection by the wait_for() method. The concatenation of this tuple is the full string which should be returned to the user.

I haven't tested, but I believe this method could be fixed to comply with the documentation by:

Change line 113 of lib/jnpr/junos/utils/start_shell.py from:
got = self.wait_for(this)

to:
got = ''.join(self.wait_for(this))

and change line 120 from:
return got
to
return (self.last_ok,got)

Since this would change the behavior of this method, we would need to double check for any code that currently uses the run() method....

**Comment by vnitinv** [comment]
Hi @akbhat How about you sending the pull request with above mentioned changes. We can test the same and merge if all goes well.

**Comment by EusaHues** [comment]
+1 on the inconsistent return tuples being "unhelpful". That part at least needs fixed.
Please don't just "fix" by updating the function document to match current (unhelpful/broken) behavior.

**Comment by vnitinv** [comment]
fixed in #445
