### ISSUE TITLE
jnpr.junos.utils.scp, no bool return type for .put() and .get()

### ISSUE THREAD

**Issue by sidhujasminder** [Juniper/py-junos-eznc#670]
rsp = scp.get('/root/file.txt', local_path='sample_path')
The output of scp, rsp should be of type of boolean type, whereas it is of type 'NoneType'.
 Boolean value would make it more easier to clearly know whether the transfer happened or not.

**Comment by stacywsmith** [comment]
@jsidhu43 We can definitely improve the documentation for thes `get()` and `put()` methods.

However, we probably won't change the return value. These methods are directly inherited from the Python `scp` module. So, it's really the `scp` module which defines the return value of these methods. Like many Python methods/functions, they don't need to return a boolean success/fail value because they will raise an exception if there's a failure.
