### ISSUE TITLE
Invalid dev.cli results in a lot of failure messages.

### ISSUE THREAD

**Issue by amanand** [Juniper/py-junos-eznc#704]
I was just trying to see if I can enter into configure mode through dev.cli or not using the following:
print dev.cli("config", warning=False)

I guess this is a negative test, but still this should not result into so many failure messages on the device: 
Apr 19 10:56:58  foo1 mgd[4642]: UI_NETCONF_ERROR: NETCONF error: syntax error, expecting </command>
Apr 19 10:56:58  foo1 last message repeated 662 times.
I do see the following error in my PyCharm window:
File "/usr/local/lib/python2.7/site-packages/ncclient/operations/rpc.py", line 343, in _request
    raise TimeoutExpiredError('ncclient timed out while waiting for an rpc reply.')
ncclient.operations.errors.TimeoutExpiredError: ncclient timed out while waiting for an rpc reply.

I guess the netconf error is either not propagating or not getting parsed correctly by the infra.

**Comment by stacywsmith** [comment]
PyEZ is designed to interact with the device using a programmatic interface (XML RPCs over NETCONF). It is not intended to simply automate CLI interaction with the device.

The `cli()` method is actually misnamed. It does not send a CLI command to the device. Instead it attempts to execute the equivalent of a CLI command using the `<command>` RPC. There are a couple implications to this implementation:
1) You can not use pipe modifiers (i.e. `| match foo`) with the `cli()` method.
2) You can not execute CLI commands which require CLI interactivity, such as `configure`, `start shell`, or `monitor traffic`.

PyEZ provides programmatic interfaces for configuring the device. For information on those APIs, look at: http://junos-pyez.readthedocs.io/en/2.1.1/jnpr.junos.utils.html#module-jnpr.junos.utils.config

In your particular example, sending the string `config` as the value of the `<command>` RPC is actually triggering a Junos bug which leaves the NETCONF session to the device in an unexpected, and apparently unrecoverable, state because it actually attempts to enter configuration mode even though the NETCONF session can't support this.

Here's a direct capture of the equivalent NETCONF interaction:
```
user@h0:~/$ ssh -s -p830 user@r0 netconf
Password:
<!-- No zombies were killed during the creation of this user interface -->
<!-- user user, class j-super-user -->
<hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <capabilities>
    <capability>urn:ietf:params:netconf:base:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:candidate:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:confirmed-commit:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:validate:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:url:1.0?scheme=http,ftp,file</capability>
    <capability>urn:ietf:params:xml:ns:netconf:base:1.0</capability>
    <capability>urn:ietf:params:xml:ns:netconf:capability:candidate:1.0</capability>
    <capability>urn:ietf:params:xml:ns:netconf:capability:confirmed-commit:1.0</capability>
    <capability>urn:ietf:params:xml:ns:netconf:capability:validate:1.0</capability>
    <capability>urn:ietf:params:xml:ns:netconf:capability:url:1.0?protocol=http,ftp,file</capability>
    <capability>http://xml.juniper.net/netconf/junos/1.0</capability>
    <capability>http://xml.juniper.net/dmi/system/1.0</capability>
  </capabilities>
  <session-id>82287</session-id>
</hello>
]]>]]>
<rpc><command>config</command></rpc>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:junos="http://xml.juniper.net/junos/16.1R4/junos">
<output>Entering configuration mode</output>
<cli>
<prompt-change>&gt;#</prompt-change>
<history-mode>1</history-mode>
</cli>
<cli>
<banner>[edit]</banner>
</cli>
</rpc-reply>
<rpc-reply>
<rpc-error>
<error-type>protocol</error-type>
<error-tag>operation-failed</error-tag>
<error-severity>error</error-severity>
<error-message>
internal communications error (tag 'command')
</error-message>
</rpc-error>
</rpc-reply>
<output>Exiting configuration mode</output>
<cli>
<prompt-change>#&gt;</prompt-change>
<history-mode>0</history-mode>
</cli>
<cli>
<banner></banner>
</cli>
<!-- netconf error: syntax error, expecting &lt;/command&gt; -->
<!-- netconf error: syntax error, expecting &lt;/command&gt; -->
<rpc><get-software-information/></rpc>
<!-- netconf error: syntax error, expecting &lt;/command&gt; -->
<!-- netconf error: syntax error, expecting &lt;/command&gt; -->
<!-- netconf error: syntax error, expecting &lt;/command&gt; -->
<!-- netconf error: syntax error, expecting &lt;/command&gt; -->
<!-- netconf error: syntax error, expecting &lt;/command&gt; -->
^Cuser@h0:~/$ 
```
