### ISSUE TITLE
facts RE uptime with virtual chassis where RE fpc number > 1

### ISSUE THREAD

**Issue by lampwins** [Juniper/py-junos-eznc#750]
The facts output includes `RE0` and `RE1` which are really intended for cases when the device has dual routing engines in a single chassis. This does not play well with a virtual chassis stack when the routing engines are in fpc positions greater than either 0 or 1. 

This came about because I wanted to obtain the uptime for a routing engine in the stack. The `uptime` is included the RE dicts when they are available in `RE0` and `RE1`. `re_info['default']` contains all the same information _except_ for uptime. I would like to have `uptime` added to the RE dicts in `re_info` to solve this issue.

**Comment by stacywsmith** [comment]
`uptime` was intentionally excluded from the new `re_info` fact because it's not really a "fact". I consider "facts" to be read-only information which maintains the same value for the life of the PyEZ connection to the device. However, the value of uptime obviously changes over time. Even worse, the uptime value would always be the time at which the `re_info`, `RE0`, or `RE1` fact was retrieved, rather than the current uptime.

Of course, this is true in the older `RE0` and `RE1` facts as well, but the decision was made to maintain the current behavior of those facts for backward compatibility.

It's also worth noting that on-demand fact gathering makes things slightly less predictable. Previously, all facts were gathered when `open()` was invoked, or when `facts_refresh()` was invoked. Now, each fact is generally gathered the first time it's value is accessed. However, multiple facts might be derived from the same RPC, or one fact might be dependent upon another fact. In those cases, the fact is gathered the first time a dependent fact, or a fact derived from the same RPC, is gathered.

I would certainly be supportive of adding an `uptime()` Device method which always executes a fresh RPC to return the current uptime for all Routing Engines.

Would an `uptime()` method meet your requirement?

**Comment by lampwins** [comment]
@stacywsmith thank you for the background. With that explanation, yes I fully support an `uptime()` which returns the current uptime for each RE.

**Comment by stacywsmith** [comment]
@lampwins Would it be sufficient to always return the uptime of the current Routing Engine (the one the NETCONF connection is to) as a number of seconds, rather than returning a dictionary with the uptime of each RE?

**Comment by lampwins** [comment]
@stacywsmith yes that is sufficient for my needs.

**Comment by stacywsmith** [comment]
@lampwins Please take a look at #752 and let me know if you have any feedback.

**Comment by stacywsmith** [comment]
Addressed via #752

**Comment by lampwins** [comment]
@stacywsmith thank you, that was a very fast turn around! Would you be able to speak to the next release date? Following the tags, I couldn't really determine a hard and fast schedule.

**Comment by stacywsmith** [comment]
@lampwins Our team has already been discussing the need for a predictable patch release schedule. To date, PyEZ has not had a predictable schedule for patch releases. We have agreed internally that we will begin publishing patch releases on (at least) a monthly basis and publish new patch releases on or before the last day of the month. So, this minor enhancement will be part of 2.1.5 and will be published on or before 31 July 2017.
