### ISSUE TITLE
Exception seen when rpc.get_config is called with filter_xml set and model=True

### ISSUE THREAD

**Issue by sarathgollapudi** [Juniper/py-junos-eznc#756]
Below Exception is seen when rpc.get_config is called with filter_xml set and model=True

c1 = dh.rpc.get_config(filter_xml='interfaces',model=True)
Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.3.2\helpers\pydev\_pydevd_bundle\pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "C:\TOBY\toby\lib\jnpr\junos\rpcmeta.py", line 127, in get_config
    ns = namespace or (nmspaces.get(model.lower()) +
AttributeError: 'bool' object has no attribute 'lower'

Please fix this or document it if this is an invalid set of options.

**Comment by stacywsmith** [comment]
@d200201123 model takes a string value of `openconfig`, `custom`, or `ietf`.

This is documented here.
https://github.com/Juniper/py-junos-eznc/blob/master/lib/jnpr/junos/rpcmeta.py#L82-L85

However, I agree that the statement `When model is True and filter_xml is None, xml is enclosed under <data> so that we get junos as well as other model configurations` in the comment is somewhat confusing.

It should probably be restated as:
`When model is not None and filter_xml is None, xml is enclosed under <data> so that we get junos as well as other model configurations`

@vnitinv Could you please look at updating the above comment?

**Comment by vnitinv** [comment]
@stacywsmith I will update the comment. How about also doing a check for `model=True` and `filter_xml` being mutually exclusive.

**Comment by stacywsmith** [comment]
@vnitinv I'm not sure I understand exactly what your proposing for an additional check.

**Comment by chidanandpujar** [comment]
Document is updated via pull request and will be merged after review
https://github.com/Juniper/py-junos-eznc/pull/1282

**Comment by chidanandpujar** [comment]
Fix is merged, closing the issue.
