### ISSUE TITLE
verbosity_level in rpc calls gets translated into verbosity-level

### ISSUE THREAD

**Issue by przygienda** [Juniper/py-junos-eznc#812]
example 

> <rpc>
>         <get-multicast-route-information>
>                 <verbosity_level>detail</verbosity_level>
>         </get-multicast-route-information>
>     </rpc>

cannot be called as 

> dev.rpc.get_multicast_route_information( verbosity_level = "extensive", group = self.group)

since it gets translated into "verbosity-level"

**Comment by przygienda** [comment]
Work around is 

dev.rpc.get_multicast_route_information( extensive = True, group = self.group)

but that should be documented somewhere?

**Comment by stacywsmith** [comment]
This is a Junos bug. @vnitinv should be able to provide you with the PR number.

Up until recently, the output of `| display xml rpc` showed `<detail/>` or `<extensive/>` in its output. I am not aware of any justification  for this change in the API.

The main issue is that the Junos standard has always been to use dashes in tag names and never use underscores in tag names. The recent change in behavior violates this Junos standard.

PyEZ translates method arguments into the RPC arguments. Since method arguments are Python variables and since Python variables are not permitted to contain dashes, they must be translated to the proper RPC tag name. If the Junos standard of always using dashes and never using underscores is followed, then this is a simple substitution. If things like `verbosity_level` are permitted this becomes an unscalable set of one offs.

**Comment by przygienda** [comment]
Agree with assesement. Generally, it's a bit of a nit but as you say, important. Can't have the one-back-offs. Very impressed with PyEz by the way, especially the Yaml->tables stuff (disclousure, I'm a JNPR employee but in a completely different corner of the shop). I played first with naked paramiko, then ncclient and all of them had tons issues until I caved in and went to PyEz.

**Comment by vnitinv** [comment]
@przygienda , Internal PR number is 1305644

**Comment by rahkumar651991** [comment]
Looks to be device issue, closing it here.
